name: David Fernández i Serrano
favicon: null
layout_spectrum: 0.9812329264823347
typography_spectrum: 0.2410942104179412
title: David Fernández i Serrano personal site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6904697646386921
  lightness: 0.8465439535211772
  saturation: 0.061020162887871265
  rhythmicContrast: 0.2526265785563737
purpose: []
